services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js web application
      - "5432:5432"  # PostgreSQL database
    volumes:
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
      # Persist logs
      - app_logs:/var/log
      # Optional: mount node_modules for faster rebuilds in development
      - node_modules:/app/node_modules
      # Persist uploaded images
      - uploads_data:/app/public/uploads
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      # Database configuration with defaults (can be overridden in .env)
      - POSTGRES_DB=${POSTGRES_DB:-hackloumi}
      - POSTGRES_USER=${POSTGRES_USER:-hackloumi}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hackloumi}
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    restart: unless-stopped
    networks:
      - hackloumi_network

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local
  node_modules:
    driver: local
  uploads_data:
    driver: local

networks:
  hackloumi_network:
    driver: bridge 